package Game;

public enum Timer
{
    ENEMY_MISSILE,
    INITIATE_NEW_GAME,
    MISSILE,
    PAUSE,
    PAUSE_COUNT_DOWN,
    PLAYER_EXPLOSION,
    SHOW_EXPLOSIONS,
    SETTING_CHANGE_MESSAGE,
    SHOW_SCORE_BUBBLES,
    SHOW_SOUND_SETTING,
    STRAY_ENEMY
}